export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_USER_CERTIFICATE_PENDING = "FETCH_USER_CERTIFICATE_PENDING";
export const FETCH_USER_CERTIFICATE_PENDING_SUCCESS = "FETCH_USER_CERTIFICATE_PENDING_SUCCESS";
export const FETCH_USER_CERTIFICATE_PENDING_FAILURE = "FETCH_USER_CERTIFICATE_PENDING_FAILURE";